//
// Constants for testing
//

// Total investors for testing
const TOTAL_TEST_INVESTORS = 5;
// Contract states
const STATE_INITIAL = 0;
const STATE_BEFORE_INVESTMENT = 1;
const STATE_DURING_INVESTMENT = 2;
const STATE_AFTER_INVESTMENT = 3;
// Unlimited amount
const UNLIMITED_AMOUNT = 2**256 - 1;
// Multiplier decimals
const MULTIPLIER_DECIMALS = 1e12;
// Minimum multiplier
const MIN_MULTIPLIER = 1e12;
// Some constants to be used in tests
const TOKEN_SUPPLY = 1000000;
const NEW_MIN_AMOUNT = 100;
const NEW_MAX_AMOUNT = 100000;
const NEW_MULTIPLE_OF = 10;
const DUMMY_AMOUNT = 5000;

//
// Exports
//
module.exports = {
  TOTAL_TEST_INVESTORS: TOTAL_TEST_INVESTORS,
  STATE_INITIAL: STATE_INITIAL,
  STATE_BEFORE_INVESTMENT: STATE_BEFORE_INVESTMENT,
  STATE_DURING_INVESTMENT: STATE_DURING_INVESTMENT,
  STATE_AFTER_INVESTMENT: STATE_AFTER_INVESTMENT,
  UNLIMITED_AMOUNT: UNLIMITED_AMOUNT,
  MULTIPLIER_DECIMALS: MULTIPLIER_DECIMALS,
  MIN_MULTIPLIER: MIN_MULTIPLIER,
  TOKEN_SUPPLY: TOKEN_SUPPLY,
  NEW_MIN_AMOUNT: NEW_MIN_AMOUNT,
  NEW_MAX_AMOUNT: NEW_MAX_AMOUNT,
  NEW_MULTIPLE_OF: NEW_MULTIPLE_OF,
  DUMMY_AMOUNT: DUMMY_AMOUNT,
};
